#ifndef CLASSIC_LAUNCHER_H
#define CLASSIC_LAUNCHER_H


#define APP_VERSION_MAJOR        0
#define APP_VERSION_MINOR        0
#define APP_VERSION_MAINTENANCE  2
#define VERSION APP_VERSION_MAJOR,APP_VERSION_MINOR,APP_VERSION_MAINTENANCE

#define FILE_VERSION VERSION
#define FILE_VERSION_STRING		"0"

#define PRODUCT_VERSION VERSION
#define PRODUCT_VERSION_STRING "(alpha)0,0,2"

#define APP_BUILT_DATE_STRING __DATE__ " - " __TIME__

#endif // CLASSIC_LAUNCHER_H
